version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: worldref
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d worldref"]
      interval: 5s
      timeout: 5s
      retries: 5

  # World Referral System Application
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/worldref
      SESSION_SECRET: your-super-secret-session-key-change-this-in-production
      WORLDID_CLIENT_ID: your-worldid-client-id
      WORLDID_CLIENT_SECRET: your-worldid-client-secret
      NEXTAUTH_SECRET: your-nextauth-secret-key-change-this-in-production
      NEXTAUTH_URL: http://localhost:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: